### ISSUE TITLE
OSX Installation doesn't seem to be working

### ISSUE THREAD

**Issue by pkmishra** [sourcegraph/thyme#11]
Getting following error
`Not working Getting message You will need the OSX 'watch' command. With Homebrew installed, in your command line enter "brew install watch". You will also need to enable privileges for "Terminal" in System Preferences > Security & Privacy > Privacy > Accessibility.
See https://support.apple.com/en-us/HT202802 for details.`

I have already installed watch and also enabled accessibility setting. Here is the output from brew info watch
```
watch: stable 3.3.11 (bottled), HEAD
Executes a program periodically, showing output fullscreen
https://gitlab.com/procps-ng/procps
Conflicts with: visionmedia-watch
/usr/local/Cellar/watch/3.3.11 (8 files, 74.8K) *
  Poured from bottle on 2016-08-16 at 11:03:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/watch.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, pkg-config ✔
Required: gettext ✔
```

**Comment by herve1976** [comment]
+1 same issue

**Comment by applefreak** [comment]
I think you just then run `thyme track` to test if the installation is working.

**Comment by generalconsensus** [comment]
+1

**Comment by beyang** [comment]
Try running `xcode-select --install` to install the macOS developer tools? Alternatively, looks like you can install via Node: https://www.npmjs.com/package/osascript

**Comment by beyang** [comment]
Going to tentatively close this. Please re-open if still an issue.

**Comment by pkmishra** [comment]
I already have developer tools installed. So not sure what's the problem.

**Comment by beyang** [comment]
@pkmishra run `go get -u github.com/sourcegraph/thyme/cmd/thyme` and try again by running `thyme track`.
