### ISSUE TITLE
Failed to Install on Ubuntu

### ISSUE THREAD

**Issue by zyphlar** [sourcegraph/thyme#14]
```
$ go get -u github.com/sourcegraph/thyme/cmd/thyme
# github.com/sourcegraph/thyme/cmd/thyme
../gopkg/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:159: undefined: thyme.NewDarwinTracker
```

Removing the reference to NewDarwinTracker on that line appears to have solved the problem, since that line obviously isn't needed on a non-Darwin system.

**Comment by beyang** [comment]
Should be fixed now. Try running `go get -u github.com/sourcegraph/thyme/cmd/thyme` and try again please!
