### ISSUE TITLE
Calls to System Events are rather expensive

### ISSUE THREAD

**Issue by paulirish** [sourcegraph/thyme#18]
On my machine, calls to `thyme track` are taking 8s-17s.

![image](https://cloud.githubusercontent.com/assets/39191/17729277/3bb15f0e-6418-11e6-9940-57706261eefe.png)

During that time, one CPU core is pretty dedicated to "System Events". As an example, `time` reported a run of `thyme track` took `10.07s real` and I'm seeing the total CPU Time in Activity Monitor increase ~9s.

Any ideas? Or more data I can collect?

**Comment by paulirish** [comment]
I poked at the applescripts and the last seems to be the slowest of the set.

Tried some edits and I can reproduce improved performance with some changes to the applescript: https://github.com/sourcegraph/thyme/compare/master...paulirish:patch-1?w=1

On repeat runs its definitely faster. Though I'm not sure its faster on a "fresh" run.  (Seems nice to get rid of the second `tell` though.)

**Comment by beyang** [comment]
Thanks for looking into this and speeding it up! I couldn't figure out why it was so slow myself. Merged here: https://github.com/sourcegraph/thyme/pull/40.

![image](https://cloud.githubusercontent.com/assets/1646931/17764009/650de084-64d1-11e6-96cf-256bcd36da85.png)
