### ISSUE TITLE
Cannot download due to $GOPATH not set

### ISSUE THREAD

**Issue by Zhouzi** [sourcegraph/thyme#20]
I'm not familiar with how go works but by following the installation steps I was unable to download the package due to:

```
package github.com/sourcegraph/thyme/cmd/thyme: cannot download, $GOPATH not set. For more details see: go help gopath
```

I figured it out thanks to `go help gopath` and by googling a bit but it may be worth adding a note about that in the installation to reduce the time to get started.

**Comment by evidanary** [comment]
+1

**Comment by RinatMenyashev** [comment]
+1

**Comment by shurcooL** [comment]
An option to consider is to have pre-compiled release binaries available for download. Building from source can be made optional, for those who want to do it, or for those who want to develop Thyme.

For everyone else, pre-compiled binaries should be the fastest way to get going.

Even though building Go projects from source is extremely easy for those who are familiar with Go, it's still an extra hurdle if you don't use Go/don't have Go installed.

**Comment by beyang** [comment]
Download from here: https://github.com/sourcegraph/thyme/releases. This can replace `go get -u ...`

**Comment by lg188** [comment]
You can easily add this to your ~/.profile file:
`export GOPATH=~/.config/go `
