### ISSUE TITLE
macOS Sierra installation instructions

### ISSUE THREAD

**Issue by montogeek** [sourcegraph/thyme#27]
Hi!

Amazing tool, been waiting for this for years!

I am running Thyme on macOS Sierra following these steps:

1. Set GOPATH: `export GOPATH=/Users/user/go`
2. `go get -u github.com/sourcegraph/thyme/cmd/thyme`
3. `cd GOPATH/bin`
4. `while true; do ./thyme track -o thyme.json; sleep 30s; done;`

For some reason I can't execute `thyme` anywhere, also, I can't run `./thyme dep` because `brew install watch` is not yet compatible with macOS Sierra

**Comment by HalfVoxel** [comment]
You probably have not added $GOPATH/bin to your PATH.
See https://golang.org/doc/code.html#GOPATH

**Comment by beyang** [comment]
You don't need `watch` installed.

Try just downloading the binary directly from here: https://github.com/sourcegraph/thyme/releases

**Comment by montogeek** [comment]
Thanks!
