### ISSUE TITLE
Mac OSX El Capitan installation issues

### ISSUE THREAD

**Issue by YPCrumble** [sourcegraph/thyme#29]
Thanks for creating this, I'm excited to try it!

Installation seems pretty difficult on mac OSX - it would be great to be installed via `brew install thyme`

I'm on El Capitan version 10.11.6

I'm getting the following error when I run `thyme dep`. I have installed `watch` and enabled terminal priveleges:

> You will need the OSX 'watch' command. With Homebrew installed, in your command line enter "brew install watch". You will also need to enable privileges for "Terminal" in System Preferences > Security & Privacy > Privacy > Accessibility.
See https://support.apple.com/en-us/HT202802 for details.

Then, when I try `thyme track` anyway I get a dialog box asking "Where is nwjs?" but it won't let me select the nwjs package I subsequently installed globally in `node_modules`.

Any suggestions would be fantastic!

**Comment by HalfVoxel** [comment]
Hi

thyme dep simply lists dependencies, it's not an error.

For the second issue, see #6

**Comment by YPCrumble** [comment]
@HalfVoxel thanks for your response! Got it. It sounds like the issue is the same as #10 and #3 as well.

Sounds like I'm in the same boat as you when you said:

> Having this screen pop up every 30 seconds unfortunately makes thyme unusable for me.

**Comment by beyang** [comment]
`watch` is no longer needed. I'd assumed it came standard on *nix systems, but apparently only Linux! Instead you can just run `while true; do thyme track -o thyme.json; sleep 30s; done;` as mentioned in the updated README.

As for ease of installation, you can now just download the binary directly from https://github.com/sourcegraph/thyme/releases.

As to the "Where is nwjs?" error, could you comment on #32?

**Comment by YPCrumble** [comment]
@beyang thanks! Added my system details in #32. When I try `while true; do thyme track -o thyme.json; sleep 30s; done;` I get teh following error:

> strconv.ParseInt: parsing "missing value": invalid syntax
> 2016/08/18 10:54:05 strconv.ParseInt: parsing "missing value": invalid syntax
