### ISSUE TITLE
Name conflict with joaomoreno/Thyme

### ISSUE THREAD

**Issue by nchammas** [sourcegraph/thyme#33]
Just an FYI: There is another time tracking application also called Thyme that appears to pre-date this one by some years.

https://joaomoreno.github.io/thyme/

I stumbled upon it by searching for this project via DDG using "github thyme" as my search terms.

![screen shot 2016-08-17 at 1 49 04 pm](https://cloud.githubusercontent.com/assets/1039369/17747137/6ac31f12-6481-11e6-89af-ee731f9176f2.png)

**Comment by beyang** [comment]
Apparently, I'm not the only one out there with a taste for bad food-oriented puns.
![image](https://cloud.githubusercontent.com/assets/1646931/17761525/a96da3dc-64bc-11e6-8776-0ce5ae22779c.png)

I'm open to other name suggestions. Any nominations?

**Comment by montogeek** [comment]
TimerMe?

**Comment by nchammas** [comment]
How about the word "time" in another language?

It's an easy way out, though the name may not be as easy to remember as "Thyme". It's a bummer that there are already so many projects with that name, but I guess it's a testament to how good it is.

Anyway, I nominate **Shigan** (시간), which is "time" in Korean.

**Comment by HalfVoxel** [comment]
Good idea. Shigan also seems to be volunteering, desire or aspiration in Japanese though (according to Google translate) which might cause some confusion.

**Comment by HalfVoxel** [comment]
One can also use things from popular culture, like for example gallifrey which is the name of the home planet for the time lords in the Dr. Who series. Just trying to come up with ideas. 
I am not sure if copyright restrictions apply here or not, might want to look that up.

**Comment by nchammas** [comment]
Another angle you could take is to play on the word "tracking" and use the name of a famous animal or person known for their tracking abilities, like the Basset Hound or Bloodhound.
