### ISSUE TITLE
Command for installing Thyme did not work

### ISSUE THREAD

**Issue by cdw9** [sourcegraph/thyme#37]
The README has

``$ go get -u github.com/sourcegraph/thyme/cmd/thyme``

but to actually install, I had to use this URL:

``$ go get -u github.com/sourcegraph/thyme/tree/master/cmd/thyme``

The first command silently failed, and I would get `command not found: thyme` when trying to run a thyme command.

**Comment by HalfVoxel** [comment]
Hi

If GOPATH is not added to your PATH (see https://golang.org/doc/code.html#GOPATH) then you will need to run the thyme command from $GOPATH/bin/thyme as that is where it will be installed.

**Comment by cdw9** [comment]
ok, seems I just set the GOPATH incorrectly. thanks
