### ISSUE TITLE
[Panic] thyme show

### ISSUE THREAD

**Issue by xuta** [sourcegraph/thyme#44]
$ thyme show -i thyme_${today}.json -w stats > thyme_${today}.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xbdc60]

goroutine 1 [running]:
github.com/sourcegraph/thyme.Stats.func1(0x0, 0x82044b608, 0x568a)
        /Users/xuta/go/src/github.com/sourcegraph/thyme/show.go:17 +0x20
github.com/sourcegraph/thyme.NewTimeline(0x8203c69a0, 0x294748, 0x8203c69a0)
        /Users/xuta/go/src/github.com/sourcegraph/thyme/show.go:142 +0x3c9
github.com/sourcegraph/thyme.Stats(0x8203c69a0, 0x0, 0x0)
        /Users/xuta/go/src/github.com/sourcegraph/thyme/show.go:17 +0x46
main.(*ShowCmd).Execute(0x34fba0, 0x8203cc8c0, 0x0, 0x5, 0x0, 0x0)
        /Users/xuta/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:114 +0x595
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0x8203c0480, 0x8203c01f0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xuta/go/src/github.com/jessevdk/go-flags/parser.go:314 +0xa89
github.com/jessevdk/go-flags.(*Parser).Parse(0x8203c0480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/xuta/go/src/github.com/jessevdk/go-flags/parser.go:185 +0x9b
main.main.func1(0x0, 0x0)
        /Users/xuta/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:141 +0x2f
main.main()
        /Users/xuta/go/src/github.com/sourcegraph/thyme/cmd/thyme/main.go:148 +0x23

**Comment by HalfVoxel** [comment]
Dup of #15

**Comment by beyang** [comment]
Dupe, should be fixed now
