### ISSUE TITLE
Can't run on macOS Sierra

### ISSUE THREAD

**Issue by montogeek** [sourcegraph/thyme#47]
I can't run the program on macOS Sierra:

Steps I followed:
1. Download darwin distribution from https://github.com/sourcegraph/thyme/releases/tag/0.2
2. Set run permissions `CHMOD +x thyme-darwin-368`
3. `./thyme-darwin-368 dep`
4. `xcode-select --install`
5. Enable Accessibility permissions

But still I get the same error message:
```
👉  ./thyme-darwin-386 dep

You will need the osascript command-line utility. You can install it via the Apple developer tools ('xcode-select --install') or npm ('npm install --save osascript').

You will need to enable privileges for "Terminal" in System Preferences > Security & Privacy > Privacy > Accessibility.
See https://support.apple.com/en-us/HT202802 for details.
```
![screen shot 2016-08-18 at 10 56 22](https://cloud.githubusercontent.com/assets/1002461/17781071/5e67f000-6533-11e6-8f70-7d3b66c7a720.png)
![screen shot 2016-08-18 at 10 56 09](https://cloud.githubusercontent.com/assets/1002461/17781070/5e614f52-6533-11e6-958c-dd1aa3d4a552.png)

What else I am missing?

**Comment by rowanoulton** [comment]
@montogeek have you tried to run `thyme track`? I got the same output from `thyme dep` even after I'd made the changes it required, and my tracking works.

**Comment by montogeek** [comment]
@rowanoulton Track works, showing a JSON

**Comment by rowanoulton** [comment]
@montogeek See also [here](https://github.com/sourcegraph/thyme/issues/36#issuecomment-240533755). Looks like `thyme track` simply lists dependencies, so you should be good to go!

**Comment by montogeek** [comment]
@rowanoulton Not yet `./thyme-darwin-386 track -o thyme.json` just start and get killed inmediately

**Comment by montogeek** [comment]
When I saw the binary distributable I thought it will run the watch internally, this works:
`while true; do ./thyme-darwin-386 track -o thyme.json; sleep 30s; done;`

Thanks
