### ISSUE TITLE
Releasing binaries

### ISSUE THREAD

**Issue by AlexGustafsson** [sourcegraph/thyme#58]
_"Go provides excellent support for producing binaries for foreign platforms without having to install Go on the target" - [Dave Cheney](http://dave.cheney.net/2012/09/08/an-introduction-to-cross-compilation-with-go)_

How come there are no prebuilt binaries for thyme? It would simplify the install process greatly imho.

**Comment by denivorium** [comment]
@AlexGustafsson,

I just downloaded the linux binary from https://github.com/sourcegraph/thyme/releases. I also just opened #61, so you can take that with a grain of salt.
