### ISSUE TITLE
MacOs installation 

### ISSUE THREAD

**Issue by zinking** [sourcegraph/thyme#65]
```
zk:~/ $ go get -u github.com/sourcegraph/thyme/cmd/thyme                                                                                                                              [16:16:54]
zk:~/ $ thyme dep                                                                                                                                                                     [16:17:08]
zsh: command not found: thyme
```

OSX mavericks with Go 1.7

and what `brew` found is the one which has name collision

**Comment by jpillora** [comment]
Go installs binaries to `$GOPATH/bin/<program>`. I think brew sets `GOPATH` to `~/go`? Otherwise you can set it to where ever. You'll also need to add `$GOPATH/bin` to your `PATH` in order for zsh to find your installed Go programs.

**Comment by zinking** [comment]
thanks for the help.  more questions after that. 
1. thyme under `bin` folder has permission 111 but can't be ran when directly type `thyme dep` could be triggered to run using ./thyme
2. some more configs to come, which I don't know how to grant privilege  to console or `thyme`

```
You will need to enable privileges for "Terminal" in System Preferences > Security & Privacy > Privacy > Accessibility.
See https://support.apple.com/en-us/HT202802 for details.
```

**Comment by jpillora** [comment]
1. maybe $GOPATH/bin isn't in your PATH?
2. follow those instructions

**Comment by SFoskitt** [comment]
Same issue here - "thyme dep" attempts to start when run from root directory (as this /Users/me/Documents/Thyme/bin/thyme dep) but this "Terminal" error persists even though I have added Terminal.app in the Privacy/Accessibility settings.

**Comment by zinking** [comment]
okay, my problem is I think rhyme needs to pass in order to carry on. 
this is confusing. but obviously reading carefully would avoid
