### ISSUE TITLE
OSX El Capitan - locks up on show and track.

### ISSUE THREAD

**Issue by ranjhaasim** [sourcegraph/thyme#66]
Locks up on show and track. I've followed the instructions by calling thyme dep. 

Followed the instructions by installing Go, and adding GOPATH.

**Comment by beyang** [comment]
Please provide additional detail (the command line input and output and screenshots would be very helpful). Can you also provide system details (what's shown when you go to Apple > System Info)? I'm going to close this for now as not providing enough detail, but feel free to re-open once additional detail is provided.
