### ISSUE TITLE
All windows listed as visible with herbstluftwm, AwesomeWM

### ISSUE THREAD

**Issue by The-Compiler** [sourcegraph/thyme#7]
With my window manager ([herbstluftwm](https://www.herbstluftwm.org)), `thyme track` shows running windows correctly, but then lists all windows IDs (even windows on another workspace) as visible. How does it figure out what's visible and what isn't?

**Comment by erasche** [comment]
Same here on AwesomeWM.

![utvalg_999 039](https://cloud.githubusercontent.com/assets/458683/17724561/a658a960-6432-11e6-87ef-fcb8f139c5c9.png)

note that each of those windows are on different workspaces and not actually visible to me concurrently.

**Comment by giodamelio** [comment]
See #13

**Comment by beyang** [comment]
dupe of #24

**Comment by The-Compiler** [comment]
@beyang How can an issue be a dupe of a PR?

**Comment by beyang** [comment]
Sorry, dupe of #13. #24 addresses both.

**Comment by The-Compiler** [comment]
@beyang Both are pull requests though :wink:

**Comment by beyang** [comment]
Oops, sorry about the oversight!

**Comment by The-Compiler** [comment]
This seems to be fixed for me on herbstluftwm via #13 - @erasche can you confirm the same with AwesomeWM?

**Comment by The-Compiler** [comment]
Closing this as it definitely seems fixed.
